//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ioon.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ioon.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        *{
        ///            margin: 0;
        ///        }
        ///        .body{
        ///            width: 100%;
        ///            background-color: #f1f1f1;
        ///        }
        ///        .main{
        ///            width: 50%;
        ///            background-color: white;
        ///            text-align: center;
        ///            margin: auto;
        ///            padding-block-start: 30px;
        ///        }
        ///        .photo{
        ///            width: 226px;
        ///            height: 150px;
        ///            border: 1px solid black;
        ///            margin: auto;
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string reset_password_template {
            get {
                return ResourceManager.GetString("reset_password_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        *{
        ///            margin: 0;
        ///        }
        ///        .body{
        ///            width: 100%;
        ///            background-color: #f1f1f1;
        ///        }
        ///        .main{
        ///            width: 50%;
        ///            background-color: white;
        ///            text-align: center;
        ///            margin: auto;
        ///            padding-block-start: 30px;
        ///        }
        ///        .photo{
        ///            width: 226px;
        ///            height: 150px;
        ///            border: 1px solid black;
        ///            margin: auto;
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string verify_email_template {
            get {
                return ResourceManager.GetString("verify_email_template", resourceCulture);
            }
        }
    }
}
